

#ifndef IDC_STATIC
  #define IDC_STATIC (-1)
#endif

#define IDD_SETTINGS                          101
#define IDC_CH_BRACKETS_AUTOCOMPLETE          1001
#define IDC_BT_OK                             1004
#define IDC_BT_CANCEL                         1005
#define IDC_CH_BRACKETS_RIGHTEXISTS_OK        1008
#define IDC_ST_PLUGINSTATE                    1009
#define IDC_CH_BRACKETS_DOSINGLEQUOTE         1010
#define IDC_CH_BRACKETS_DOTAG                 1011
#define IDC_CH_BRACKETS_DOTAGIF               1012
#define IDC_ED_BRACKETS_DOTAGIF               1013
#define IDC_CH_BRACKETS_DOTAG2                1014
#define IDC_CH_BRACKETS_SKIPESCAPED           1015
#define IDC_CH_BRACKETS_SKIPESCAPED2
#define	IDD_PLUGINGOLINE_DEMO		2500
#define	ID_GOLINE_EDITDEMO	(IDD_PLUGINGOLINE_DEMO + 1)
#define	ID_GOLINE_MSG	(IDD_PLUGINGOLINE_DEMO + 2)
#define	ID_GOLINE_RELOAD	(IDD_PLUGINGOLINE_DEMO + 3)
#define	ID_GOLINE_BASEDIR	(IDD_PLUGINGOLINE_DEMO + 4)
#define	ID_UGO_STATICDEMO  (IDD_PLUGINGOLINE_DEMO + 5)
#define	ID_GOLINE_EXPORT	(IDD_PLUGINGOLINE_DEMO + 6)
